spring:
  application:
    name: userBackend
  banner:
    location: banner.txt
    charset: UTF-8

#dubbo:
#  application:
#    name: userBackend
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    id: ns-Registry
#    address: nacos://localhost:8848



