name: buildTarget
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  buildZxsCloudTarget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B -e -DskipTests=true package

      - name: Copy Build
        run: mkdir build && cp **/target/*.jar build

      - name: Zip the Build
        run: zip -r zxsIotCloud.zip build/

      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Test
        run: |
          run: echo ${{ github.sha }} > Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body_path: ${{ github.workspace }}-doc/CHANGELOG.txt
          files: |
            Release.txt
            LICENSE
            zxsIotCloud.zip
          token: ${{ secrets.RELEASE_TOKEN }}
